import camp from "../gallery/camp.jpg";
import outdoorroast from "../gallery/outdoorroast.jpg";
import streetfood from "../gallery/streetfood.jpeg";
import event from "../gallery/event.jpeg";
import privateevent from "../gallery/privateevent.jpeg";
import eggs from "../gallery/eggs.jpg";

export const servicesData = [
  {
    title: "STREET FOOD",
    content:
      "UNREAL STREET FOOD FOR REAL FOOD SNOBS. AN ECLECTIC BLEND OF FINE DINING & STREET FOOD. PRIVATE / EVENT BOOKINGS AVAILABLE. CATCH US LOCATED SEASONALLY AT POP-UP LOCATIONS & STREET FOOD MARKETS ACROSS THE COUNTRY.",
    image: streetfood,
  },
  {
    title: "IMMERSIVE DINING EVENTS",
    content:
      "AN INTIMATE NIGHT OF IMMERSIVE YET RELAXED FINE DINING. INNOVATIVE 4-6 COURSE TASTER MENU WITH A CINEMATIC WALK-THROUGH OF THE MENU, IT’S COMPONENTS & THE INSPIRATION BEHIND THE NIGHT. IMAGINE FINE DINING MEETS THE THEATRE.",
    image: privateevent,
  },
  {
    title: "PRIVATE DINING SERVICES",
    content:
      "UNFORGETTABLE ON-LOCATION FINE DINING EXPERIENCES. FROM RELAXED FAMILY DINING TO 5 COURSE FINE DINING TASTING MENUS. WE’LL WORK WITH YOU TO CREATE A BESPOKE MENU TO SUIT YOUR TASTE FROM THE FINEST LOCALLY SOURCED INGREDIENTS. AVAILABLE FROM ONE DAY, TO LONG-WEEKEND & WHOLE HOLIDAY BOOKINGS.",
    image: event,
  },
  {
    title: "WOODLAND DINNERS",
    content: "A UNIQUE SEASONAL DINING EXPERIENCE AMONG ANCIENT WOODLANDS.",
    image: outdoorroast,
  },
  {
    title: "LUXURY OVERNIGHT STAYS",
    content:
      "WAKE UP TO A LAKE-SIDE BREAKFAST IN YOUR CHOICE OF LUXURY OFF-GRID ACCOMMODATION. CHOOSE FROM SEVERAL BEAUTIFUL LOG CABINS, A LAKE HOUSE, OR THE ROMANTIC GEOMETRIC DOME, ALL WITH CENTRAL HEATING & FIRE PITS SET AMONGST A BEAUTIFUL 20-ACRE BACKDROP. BREATH WORK, VAGUS NERVE RESET & MEDITATION SESSIONS AVAILABLE WITH JACOB FROM OHMBRELLA. ",
    image: camp,
  },
  {
    title: "BRAND CONSULT-ANCY",
    content:
      "WAKE UP TO A LAKE-SIDE BREAKFAST IN YOUR CHOICE OF LUXURY OFF-GRID ACCOMMODATION. CHOOSE FROM SEVERAL BEAUTIFUL LOG CABINS, A LAKE HOUSE, OR THE ROMANTIC GEOMETRIC DOME, ALL WITH CENTRAL HEATING & FIRE PITS SET AMONGST A BEAUTIFUL 20-ACRE BACKDROP. BREATH WORK, VAGUS NERVE RESET & MEDITATION SESSIONS AVAILABLE WITH JACOB FROM OHMBRELLA. ",
    image: eggs,
  },
];
