import Head from "next/head";
import Nav from "../components/nav";
import styles from "../styles/Home.module.css";
import logo from "../public/alchemylogo.png";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>the Food Alchemist</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.titlediv}>
          <h1 className={styles.title}>THE FOOD ALCHEMIST</h1>
          <Image className={styles.logo} src={logo} alt="alchemylogo" />
        </div>

        <Nav />
      </main>
    </div>
  );
}
